#training parameters
batch_size : 256, #batch size
epochs : 20, #optimisation epochs
lr: 0.01 #learning rate
pretrained: False
second_training: True

#manifold/signal parameters
order: 2 #order to which to compute the directional derivatives
inner_product_features: True
vector: True
diffusion: False
frac_geodesic_nb: 2.0 #fraction of geodesic neighbours (relative to node degree) to map to tangent space
frac_sampled_nb: -1 #fraction of neighbours to sample for gradient computation (if -1 then all neighbours)
var_explained: 0.9 #fraction of variance explained by the local gauges

#network parameters
diffusion_method: spectral
dropout: 0. #dropout in the MLP
n_lin_layers: 2 #number of layers if MLP
hidden_channels: 16 #number of hidden channels
out_channels: 3 #number of output channels (if null, then =hidden_channels)
bias: True #learn bias parameters in MLP
vec_norm: False
batch_norm: False #batch normalisation

#other params
seed: 0 #seed for reproducibility
processes: 1