
depth: 0 #how many hops to aggregate
#training parameters
batch_size : 256, #batch size
epochs : 20, #optimisation epochs
lr: 0.01 #learning rate

#manifold/signal parameters
order: 2 #order to which to compute the directional derivatives
inner_product_features: True
vector: True
diffusion: True
frac_geodesic_nb: 2.0 #fraction of geodesic neighbours (relative to node degree) to map to tangent space
var_explained: 0.9 #fraction of variance explained by the local gauges

#network parameters
frac_sampled_nb: 0.8 #fraction of neighbours to consider during nhood sampling
dropout: 0. #dropout in the MLP
n_lin_layers: 2 #number of layers if MLP
hidden_channels: 16 #number of hidden channels
out_channels: null #number of output channels (if null, then =hidden_channels)
bias: False #learn bias parameters in MLP
batch_norm: True #batch normalisation

#other params
seed: 0 #seed for reproducibility